<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="SimpleExample">
    <eClassifiers xsi:type="ecore:EClass" name="ConceptA">
      <eStructuralFeatures xsi:type="ecore:EReference" name="Bs" upperBound="-1" eType="/0/ConceptB" containment="true" eOpposite="/0/ConceptB/ConceptA"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Cs" upperBound="-1" eType="/0/ConceptC" containment="true" eOpposite="/0/ConceptC/ConceptA"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConceptB">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ConceptA" ordered="false" lowerBound="1" eType="/0/ConceptA" eOpposite="/0/ConceptA/Bs"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ReferencedC" ordered="false" eType="/0/BReferencesC" eOpposite="/0/BReferencesC/ReferringBs"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConceptC">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ConceptA" ordered="false" lowerBound="1" eType="/0/ConceptA" eOpposite="/0/ConceptA/Cs"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ReferringBs" upperBound="-1" eType="/0/BReferencesC" eOpposite="/0/BReferencesC/ReferencedC"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BReferencesC">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Property" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ReferringBs" ordered="false" upperBound="-1" eType="/0/ConceptB" eOpposite="/0/ConceptB/ReferencedC"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ReferencedC" ordered="false" eType="/0/ConceptC" eOpposite="/0/ConceptC/ReferringBs"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Double"/>
  </ecore:EPackage>
</xmi:XMI>
