<?xml version="1.0" encoding="ISO-8859-1"?>
<Metamodel xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="KM3" location="1:1-103:2">
  <contents location="1:1-94:2" name="KM3">
    <contents xsi:type="Class" location="2:9-7:10" name="LocatedElement" isAbstract="true">
      <structuralFeatures xsi:type="Attribute" location="3:17-3:45" name="location" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.1/@contents.2"/>
      <structuralFeatures xsi:type="Attribute" location="4:17-4:62" name="commentsBefore" lower="0" upper="-1" isOrdered="true" isUnique="false" type="//@contents.1/@contents.2"/>
      <structuralFeatures xsi:type="Attribute" location="5:17-5:61" name="commentsAfter" lower="0" upper="-1" isOrdered="true" isUnique="false" type="//@contents.1/@contents.2"/>
    </contents>
    <contents xsi:type="Class" location="9:9-13:10" name="ModelElement" isAbstract="true" supertypes="//@contents.0/@contents.0">
      <structuralFeatures xsi:type="Attribute" location="10:17-10:41" name="name" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.1/@contents.2"/>
      <structuralFeatures xsi:type="Reference" location="11:17-11:67" name="package" lower="1" upper="1" isOrdered="false" type="//@contents.0/@contents.14" isContainer="false" opposite="//@contents.0/@contents.14/@structuralFeatures.0"/>
    </contents>
    <contents xsi:type="Class" location="15:9-17:10" name="Classifier" isAbstract="false" supertypes="//@contents.0/@contents.1"/>
    <contents xsi:type="Class" location="19:9-21:10" name="DataType" isAbstract="false" supertypes="//@contents.0/@contents.2"/>
    <contents xsi:type="Class" location="23:9-26:10" name="Enumeration" isAbstract="false" supertypes="//@contents.0/@contents.2">
      <structuralFeatures xsi:type="Reference" location="24:17-24:87" name="literals" lower="0" upper="-1" isOrdered="true" type="//@contents.0/@contents.5" isContainer="true" opposite="//@contents.0/@contents.5/@structuralFeatures.0"/>
    </contents>
    <contents xsi:type="Class" location="28:9-31:10" name="EnumLiteral" isAbstract="false" supertypes="//@contents.0/@contents.1">
      <structuralFeatures xsi:type="Reference" location="29:17-29:66" name="enum" lower="1" upper="1" isOrdered="false" type="//@contents.0/@contents.4" isContainer="false" opposite="//@contents.0/@contents.4/@structuralFeatures.0"/>
    </contents>
    <contents xsi:type="Class" location="33:9-35:10" name="TemplateParameter" isAbstract="false" supertypes="//@contents.0/@contents.2"/>
    <contents xsi:type="Class" location="37:9-44:10" name="Class" isAbstract="false" supertypes="//@contents.0/@contents.2">
      <structuralFeatures xsi:type="Reference" location="38:17-38:79" name="parameters" lower="0" upper="-1" isOrdered="true" type="//@contents.0/@contents.6" isContainer="true"/>
      <structuralFeatures xsi:type="Attribute" location="39:17-39:48" name="isAbstract" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.1/@contents.0"/>
      <structuralFeatures xsi:type="Reference" location="40:17-40:49" name="supertypes" lower="0" upper="-1" isOrdered="false" type="//@contents.0/@contents.7" isContainer="false"/>
      <structuralFeatures xsi:type="Reference" location="41:17-41:104" name="structuralFeatures" lower="0" upper="-1" isOrdered="true" type="//@contents.0/@contents.9" isContainer="true" opposite="//@contents.0/@contents.9/@structuralFeatures.0"/>
      <structuralFeatures xsi:type="Reference" location="42:17-42:88" name="operations" lower="0" upper="-1" isOrdered="true" type="//@contents.0/@contents.12" isContainer="true" opposite="//@contents.0/@contents.12/@structuralFeatures.0"/>
    </contents>
    <contents xsi:type="Class" location="46:9-53:10" name="TypedElement" isAbstract="false" supertypes="//@contents.0/@contents.1">
      <structuralFeatures xsi:type="Attribute" location="47:17-47:43" name="lower" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.1/@contents.1"/>
      <structuralFeatures xsi:type="Attribute" location="48:17-48:43" name="upper" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.1/@contents.1"/>
      <structuralFeatures xsi:type="Attribute" location="49:17-49:47" name="isOrdered" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.1/@contents.0"/>
      <structuralFeatures xsi:type="Attribute" location="50:17-50:46" name="isUnique" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.1/@contents.0"/>
      <structuralFeatures xsi:type="Reference" location="51:17-51:45" name="type" lower="1" upper="1" isOrdered="false" type="//@contents.0/@contents.2" isContainer="false"/>
    </contents>
    <contents xsi:type="Class" location="55:9-60:10" name="StructuralFeature" isAbstract="false" supertypes="//@contents.0/@contents.8">
      <structuralFeatures xsi:type="Reference" location="56:17-56:71" name="owner" lower="1" upper="1" isOrdered="false" type="//@contents.0/@contents.7" isContainer="false" opposite="//@contents.0/@contents.7/@structuralFeatures.3"/>
      <structuralFeatures xsi:type="Reference" location="57:17-57:82" name="subsetOf" lower="0" upper="-1" isOrdered="false" type="//@contents.0/@contents.9" isContainer="false" opposite="//@contents.0/@contents.9/@structuralFeatures.2"/>
      <structuralFeatures xsi:type="Reference" location="58:17-58:82" name="derivedFrom" lower="0" upper="-1" isOrdered="false" type="//@contents.0/@contents.9" isContainer="false" opposite="//@contents.0/@contents.9/@structuralFeatures.1"/>
    </contents>
    <contents xsi:type="Class" location="62:9-64:10" name="Attribute" isAbstract="false" supertypes="//@contents.0/@contents.9"/>
    <contents xsi:type="Class" location="66:9-70:10" name="Reference" isAbstract="false" supertypes="//@contents.0/@contents.9">
      <structuralFeatures xsi:type="Attribute" location="67:17-67:49" name="isContainer" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.1/@contents.0"/>
      <structuralFeatures xsi:type="Reference" location="68:17-68:53" name="opposite" lower="0" upper="1" isOrdered="false" type="//@contents.0/@contents.11" isContainer="false"/>
    </contents>
    <contents xsi:type="Class" location="72:9-76:10" name="Operation" isAbstract="false" supertypes="//@contents.0/@contents.8">
      <structuralFeatures xsi:type="Reference" location="73:17-73:63" name="owner" lower="1" upper="1" isOrdered="false" type="//@contents.0/@contents.7" isContainer="false" opposite="//@contents.0/@contents.7/@structuralFeatures.4"/>
      <structuralFeatures xsi:type="Reference" location="74:17-74:88" name="parameters" lower="0" upper="-1" isOrdered="true" type="//@contents.0/@contents.13" isContainer="true" opposite="//@contents.0/@contents.13/@structuralFeatures.0"/>
    </contents>
    <contents xsi:type="Class" location="78:9-81:10" name="Parameter" isAbstract="false" supertypes="//@contents.0/@contents.8">
      <structuralFeatures xsi:type="Reference" location="79:17-79:67" name="owner" lower="1" upper="1" isOrdered="false" type="//@contents.0/@contents.12" isContainer="false" opposite="//@contents.0/@contents.12/@structuralFeatures.1"/>
    </contents>
    <contents xsi:type="Class" location="83:9-87:10" name="Package" isAbstract="false" supertypes="//@contents.0/@contents.1">
      <structuralFeatures xsi:type="Reference" location="84:17-84:93" name="contents" lower="0" upper="-1" isOrdered="true" type="//@contents.0/@contents.1" isContainer="true" opposite="//@contents.0/@contents.1/@structuralFeatures.1"/>
      <structuralFeatures xsi:type="Reference" location="85:17-85:69" name="metamodel" lower="1" upper="1" isOrdered="false" type="//@contents.0/@contents.15" isContainer="false" opposite="//@contents.0/@contents.15/@structuralFeatures.0"/>
    </contents>
    <contents xsi:type="Class" location="89:9-92:10" name="Metamodel" isAbstract="false" supertypes="//@contents.0/@contents.0">
      <structuralFeatures xsi:type="Reference" location="90:17-90:88" name="contents" lower="0" upper="-1" isOrdered="true" type="//@contents.0/@contents.14" isContainer="true" opposite="//@contents.0/@contents.14/@structuralFeatures.1"/>
    </contents>
  </contents>
  <contents location="96:1-103:2" name="PrimitiveTypes">
    <contents xsi:type="DataType" location="97:9-97:26" name="Boolean"/>
    <contents xsi:type="DataType" location="99:9-99:26" name="Integer"/>
    <contents xsi:type="DataType" location="101:9-101:25" name="String"/>
  </contents>
</Metamodel>
