<?xml version="1.0" encoding="ISO-8859-1"?>
<km3:Metamodel xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:km3="http://www.eclipse.org/gmt/2005/KM3" location="1:1-12:2">
  <contents name="exampleB">
    <contents xsi:type="km3:Class" location="3:2-5:3" name="A"/>
    <contents xsi:type="km3:Class" location="7:2-9:3" name="C">
      <structuralFeatures xsi:type="km3:Reference" name="a" lower="1" upper="1" type="//@contents.0/@contents.2" opposite="//@contents.0/@contents.2/@structuralFeatures.0"/>
    </contents>
    <contents xsi:type="km3:Class" location="11:2-11:22" name="B">
      <structuralFeatures xsi:type="km3:Reference" name="cr" lower="1" upper="1" type="//@contents.0/@contents.1" opposite="//@contents.0/@contents.1/@structuralFeatures.0"/>
    </contents>
  </contents>
</km3:Metamodel>
