<?xml version="1.0" encoding="ISO-8859-1"?>
<km3:Metamodel xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:km3="http://www.eclipse.org/gmt/2005/KM3" location="1:1-14:2">
  <contents name="example">
    <contents xsi:type="km3:Class" name="A">
      <structuralFeatures xsi:type="km3:Reference" location="3:17-3:53" name="BTotalOrder" lower="1" upper="1" type="//@contents.0/@contents.3"/>
      <structuralFeatures xsi:type="km3:Reference" location="4:17-4:53" name="CTotalOrder" lower="1" upper="1" type="//@contents.0/@contents.3"/>
    </contents>
    <contents xsi:type="km3:Class" name="B"/>
    <contents xsi:type="km3:Class" name="C"/>
    <contents xsi:type="km3:Class" name="ATotalOrder" isAbstract="true" supertypes="//@contents.0/@contents.1 //@contents.0/@contents.2">
      <structuralFeatures xsi:type="km3:Reference" location="8:17-8:47" name="BOppositeTotalOrder" lower="1" upper="1" type="//@contents.0/@contents.0" opposite="//@contents.0/@contents.0/@structuralFeatures.0"/>
      <structuralFeatures xsi:type="km3:Reference" location="12:17-12:47" name="COppositeTotalOrder" lower="1" upper="1" type="//@contents.0/@contents.0" opposite="//@contents.0/@contents.0/@structuralFeatures.1"/>
    </contents>
  </contents>
</km3:Metamodel>
