<?xml version="1.0" encoding="ISO-8859-1"?>
<Editor xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns="Editor" extension="mgm">
  <block type="CommentsLine" blockbegin="--" blockend="">
    <format>
      <color red="0" green="130" blue="0"/>
      <font font="times" italic="true"/>
    </format>
  </block>
  <block type="string" blockbegin="&quot;" blockend="&quot;" esc="\">
    <format>
      <color red="0" green="0" blue="255"/>
      <font font="times"/>
    </format>
  </block>
  <group type="keywords">
    <format>
      <color red="127" green="0" blue="85"/>
      <font font="times" bold="true"/>
    </format>
    <element element="Found"/>
    <element element="duplicate lines in"/>
    <element element="blocks in"/>
    <element element="files"/>
    <element element="Processed a total of"/>
    <element element="significant ("/>
    <element element="raw) lines in"/>
    <element element="Processing time:"/>
    <element element="sec"/>
    <element element="the following files:"/>
    <element element="Between lines"/>
    <element element="and"/>
    <element element="in"/>
  </group>
  <group type="symbols">
    <format>
      <color red="127" green="0" blue="85"/>
      <font font="times" bold="true"/>
    </format>
    <element element="["/>
    <element element="]"/>
    <element element="!"/>
    <element element=","/>
    <element element="("/>
    <element element=")"/>
    <element element="{"/>
    <element element="}"/>
    <element element=";"/>
    <element element="|"/>
    <element element="#"/>
    <element element="?"/>
    <element element="::"/>
    <element element="."/>
    <element element="->"/>
    <element element="-"/>
    <element element="*"/>
    <element element="/"/>
    <element element="+"/>
    <element element="="/>
    <element element=">"/>
    <element element="&lt;"/>
    <element element=">="/>
    <element element="&lt;="/>
    <element element="&lt;>"/>
    <element element="&lt;-"/>
  </group>
  <group type="types">
    <format>
      <color red="42" green="0" blue="255"/>
      <font font="times" bold="true"/>
    </format>
    <element element="String"/>
    <element element="String"/>
    <element element="Integer"/>
    <element element="Double"/>
  </group>
</Editor>
