<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="CodeClone">
    <eClassifiers xsi:type="ecore:EClass" name="LocatedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="commentsBefore" unique="false" upperBound="-1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="commentsAfter" unique="false" upperBound="-1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CodeClone" eSuperTypes="/0/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceToolName" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1" eType="/0/CloneGroup" containment="true" eOpposite="/0/CloneGroup/parent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fl" ordered="false" lowerBound="1" eType="/0/FileList" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CloneGroup" eSuperTypes="/0/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalUnits" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" ordered="false" eType="/0/CodeClone" eOpposite="/0/CodeClone/groups"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="units" lowerBound="1" upperBound="-1" eType="/0/CloneUnit" containment="true" eOpposite="/0/CloneUnit/parent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CloneUnit" eSuperTypes="/0/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" ordered="false" eType="/0/CloneGroup" eOpposite="/0/CloneGroup/units"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startLine" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="endLine" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalLines" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="file" ordered="false" lowerBound="1" eType="/0/File"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FileList" eSuperTypes="/0/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="files" upperBound="-1" eType="/0/File" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="File" eSuperTypes="/0/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalFileLines" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  </ecore:EPackage>
</xmi:XMI>
