<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="Simian">
    <eClassifiers xsi:type="ecore:EClass" name="LocatedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="commentsBefore" unique="false" upperBound="-1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="commentsAfter" unique="false" upperBound="-1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ClonePairs" eSuperTypes="/0/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="clonepart" ordered="false" upperBound="-1" eType="/0/ClonePair" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="summary" ordered="false" lowerBound="1" eType="/0/Summary" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Summary" eSuperTypes="/0/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="total_lines" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="total_blocks" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="clone_files" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sig_lines" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="raw_lines" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="total_files" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="process_time" ordered="false" unique="false" lowerBound="1" eType="/1/Double"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ClonePair" eSuperTypes="/0/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="totallines" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="clonesubpart" ordered="false" upperBound="-1" eType="/0/Clone" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Clone" eSuperTypes="/0/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="start_line" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="end_line" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Double"/>
  </ecore:EPackage>
</xmi:XMI>
