<?xml version="1.0" encoding="ISO-8859-1"?>
<Implementation xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns="MADL">
  <modules name="SpeedSensor"/>
  <modules name="TransMotor"/>
  <modules name="DataSensor"/>
  <modules name="ArmControl">
    <uses uses="//@modules.0"/>
    <uses uses="//@modules.6"/>
    <uses uses="//@modules.1"/>
  </modules>
  <modules name="DiskReader">
    <uses uses="//@modules.2"/>
    <uses uses="//@modules.0"/>
  </modules>
  <modules name="PlayerControl">
    <uses uses="//@modules.4"/>
    <uses uses="//@modules.3"/>
  </modules>
  <modules name="TrackSensor"/>
</Implementation>
