<?xml version="1.0" encoding="ISO-8859-1"?>
<Implementation xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns="MADL">
  <modules name="TrackSensor">
    <classes name="TrackSensor"/>
  </modules>
  <modules name="OutputControl">
    <classes name="OutputControl" calls="//@modules.1/@classes.0 //@modules.6/@classes.0"/>
    <uses uses="//@modules.6"/>
    <uses uses="//@modules.1"/>
  </modules>
  <modules name="TransMotor">
    <classes name="TransMotor" calls="//@modules.2/@classes.0"/>
    <uses uses="//@modules.2"/>
  </modules>
  <modules name="DataSensor">
    <classes name="DataSensor"/>
  </modules>
  <modules name="PlayerControl">
    <classes name="PlayerControl" calls="//@modules.2/@classes.0 //@modules.4/@classes.0 //@modules.5/@classes.0 //@modules.7/@classes.0"/>
    <uses uses="//@modules.4"/>
    <uses uses="//@modules.2"/>
    <uses uses="//@modules.7"/>
    <uses uses="//@modules.5"/>
  </modules>
  <modules name="DiscReader">
    <classes name="DiscReader" calls="//@modules.3/@classes.0 //@modules.5/@classes.0"/>
    <uses uses="//@modules.3"/>
    <uses uses="//@modules.5"/>
  </modules>
  <modules name="NotePlayer">
    <classes name="NotePlayer" calls="//@modules.6/@classes.0"/>
    <uses uses="//@modules.6"/>
  </modules>
  <modules name="ArmControl">
    <classes name="ArmControl" calls="//@modules.0/@classes.0 //@modules.2/@classes.0 //@modules.7/@classes.0"/>
    <uses uses="//@modules.0"/>
    <uses uses="//@modules.2"/>
    <uses uses="//@modules.7"/>
  </modules>
  <modules name="Play">
    <classes name="Play"/>
  </modules>
</Implementation>
