<?xml version="1.0" encoding="ISO-8859-1"?>
<Root xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="XML" startLine="2" endLine="25" name="feed">
  <children xsi:type="Text" startLine="2" name="#text" value="&#xA;"/>
  <children xsi:type="Text" startLine="3" name="#text" value="&#xA;"/>
  <children xsi:type="Text" startLine="4" name="#text" value=" "/>
  <children xsi:type="Element" startLine="4" endLine="4" name="title">
    <children xsi:type="Text" startLine="4" name="#text" value="Example ATOM"/>
  </children>
  <children xsi:type="Text" startLine="4" name="#text" value="&#xA;"/>
  <children xsi:type="Text" startLine="5" name="#text" value=" "/>
  <children xsi:type="Element" startLine="5" endLine="5" name="subtitle">
    <children xsi:type="Text" startLine="5" name="#text" value="Insert witty or insightful remark here"/>
  </children>
  <children xsi:type="Text" startLine="5" name="#text" value="&#xA;"/>
  <children xsi:type="Text" startLine="6" name="#text" value=" "/>
  <children xsi:type="Element" startLine="6" endLine="6" name="id">
    <children xsi:type="Text" startLine="6" name="#text" value="urn:uuid:60a76c80-d399-11d9-b91C-0003939e0af6"/>
  </children>
  <children xsi:type="Text" startLine="6" name="#text" value="&#xA;"/>
  <children xsi:type="Text" startLine="7" name="#text" value=" "/>
  <children xsi:type="Element" startLine="7" endLine="7" name="link">
    <children xsi:type="Attribute" name="href" value="http://example.org"/>
  </children>
  <children xsi:type="Text" startLine="7" name="#text" value="&#xA;"/>
  <children xsi:type="Text" startLine="8" name="#text" value=" "/>
  <children xsi:type="Element" startLine="8" endLine="8" name="updated">
    <children xsi:type="Text" startLine="8" name="#text" value="2003-12-13T18:30:02Z"/>
  </children>
  <children xsi:type="Text" startLine="8" name="#text" value="&#xA;"/>
  <children xsi:type="Text" startLine="9" name="#text" value=" "/>
  <children xsi:type="Element" startLine="9" endLine="9" name="category">
    <children xsi:type="Attribute" name="term" value="Film"/>
    <children xsi:type="Attribute" name="scheme" value="lesheme1"/>
    <children xsi:type="Attribute" name="label" value="lelabel"/>
  </children>
  <children xsi:type="Text" startLine="9" name="#text" value="&#xA;"/>
  <children xsi:type="Text" startLine="10" name="#text" value=" "/>
  <children xsi:type="Element" startLine="10" endLine="10" name="category">
    <children xsi:type="Attribute" name="term" value="Movie"/>
    <children xsi:type="Attribute" name="scheme" value="lesheme2"/>
    <children xsi:type="Attribute" name="label" value="lelabel"/>
  </children>
  <children xsi:type="Text" startLine="10" name="#text" value="&#xA;"/>
  <children xsi:type="Text" startLine="11" name="#text" value=" "/>
  <children xsi:type="Element" startLine="11" endLine="14" name="author">
    <children xsi:type="Text" startLine="11" name="#text" value="&#xA;"/>
    <children xsi:type="Text" startLine="12" name="#text" value="   "/>
    <children xsi:type="Element" startLine="12" endLine="12" name="name">
      <children xsi:type="Text" startLine="12" name="#text" value="John Doe"/>
    </children>
    <children xsi:type="Text" startLine="12" name="#text" value="&#xA;"/>
    <children xsi:type="Text" startLine="13" name="#text" value="   "/>
    <children xsi:type="Element" startLine="13" endLine="13" name="email">
      <children xsi:type="Text" startLine="13" name="#text" value="johndoe@example.com"/>
    </children>
    <children xsi:type="Text" startLine="13" name="#text" value="&#xA;"/>
    <children xsi:type="Text" startLine="14" name="#text" value=" "/>
  </children>
  <children xsi:type="Text" startLine="14" name="#text" value="&#xA;"/>
  <children xsi:type="Text" startLine="15" name="#text" value=" "/>
  <children xsi:type="Text" startLine="15" name="#text" value="&#xA;"/>
  <children xsi:type="Text" startLine="16" name="#text" value="&#xA;"/>
  <children xsi:type="Text" startLine="17" name="#text" value=" "/>
  <children xsi:type="Element" startLine="17" endLine="23" name="entry">
    <children xsi:type="Text" startLine="17" name="#text" value="&#xA;"/>
    <children xsi:type="Text" startLine="18" name="#text" value="   "/>
    <children xsi:type="Element" startLine="18" endLine="18" name="title">
      <children xsi:type="Text" startLine="18" name="#text" value="Atom-Powered Robots Run Amok"/>
    </children>
    <children xsi:type="Text" startLine="18" name="#text" value="&#xA;"/>
    <children xsi:type="Text" startLine="19" name="#text" value="   "/>
    <children xsi:type="Element" startLine="19" endLine="19" name="link">
      <children xsi:type="Attribute" name="href" value="http://example.org/2003/12/13/atom03"/>
    </children>
    <children xsi:type="Text" startLine="19" name="#text" value="&#xA;"/>
    <children xsi:type="Text" startLine="20" name="#text" value="   "/>
    <children xsi:type="Element" startLine="20" endLine="20" name="id">
      <children xsi:type="Text" startLine="20" name="#text" value="urn:uuid:1225c695-cfb8-4ebb-aaaa-80da344efa6a"/>
    </children>
    <children xsi:type="Text" startLine="20" name="#text" value="&#xA;"/>
    <children xsi:type="Text" startLine="21" name="#text" value="   "/>
    <children xsi:type="Element" startLine="21" endLine="21" name="updated">
      <children xsi:type="Text" startLine="21" name="#text" value="2003-12-13T18:30:02Z"/>
    </children>
    <children xsi:type="Text" startLine="21" name="#text" value="&#xA;"/>
    <children xsi:type="Text" startLine="22" name="#text" value="   "/>
    <children xsi:type="Element" startLine="22" endLine="22" name="summary">
      <children xsi:type="Text" startLine="22" name="#text" value="Some text."/>
    </children>
    <children xsi:type="Text" startLine="22" name="#text" value="&#xA;"/>
    <children xsi:type="Text" startLine="23" name="#text" value=" "/>
  </children>
  <children xsi:type="Text" startLine="23" name="#text" value="&#xA;"/>
  <children xsi:type="Text" startLine="24" name="#text" value="&#xA;"/>
</Root>
