<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="XML">
  <Root name="Channel">
    <children xsi:type="Element" name="title">
      <children xsi:type="Text" name="letitle" value="Example ATOM"/>
    </children>
    <children xsi:type="Element" name="link">
      <children xsi:type="Text" name="thelink" value="http://example.org"/>
    </children>
    <children xsi:type="Element" name="description">
      <children xsi:type="Text" name="ladescription" value="Insert witty or insightful remark here"/>
    </children>
    <children xsi:type="Element" name="language">
      <children xsi:type="Text" name="lelangage" value=""/>
    </children>
    <children xsi:type="Element" name="copyright">
      <children xsi:type="Text" name="thecopyright" value=""/>
    </children>
    <children xsi:type="Element" name="managingEditor">
      <children xsi:type="Text" name="themanagingEditor" value="John Doe"/>
    </children>
    <children xsi:type="Element" name="webmaster">
      <children xsi:type="Text" name="thewebmaster" value="johndoe@example.com"/>
    </children>
    <children xsi:type="Element" name="generator">
      <children xsi:type="Text" name="thegenerator" value=""/>
    </children>
    <children xsi:type="Element" name="pubDate">
      <children xsi:type="Text" name="thepubDate" value=""/>
    </children>
    <children xsi:type="Element" name="lastBuildDate">
      <children xsi:type="Text" name="thelastBuildDate" value="2003-12-13T18:30:02Z"/>
    </children>
    <children xsi:type="Element" name="items">
      <children xsi:type="Element" name="Item">
        <children xsi:type="Element" name="title">
          <children xsi:type="Text" name="letitle" value="Atom-Powered Robots Run Amok"/>
        </children>
        <children xsi:type="Element" name="link">
          <children xsi:type="Text" name="thelink" value="http://example.org/2003/12/13/atom03"/>
        </children>
        <children xsi:type="Element" name="comments">
          <children xsi:type="Text" name="thecomments" value="Some text."/>
        </children>
        <children xsi:type="Element" name="description">
          <children xsi:type="Text" name="thedescription" value=""/>
        </children>
        <children xsi:type="Element" name="author">
          <children xsi:type="Text" name="theauthor" value=""/>
        </children>
        <children xsi:type="Element" name="guid">
          <children xsi:type="Text" name="theguid" value="urn:uuid:1225c695-cfb8-4ebb-aaaa-80da344efa6a"/>
        </children>
        <children xsi:type="Element" name="category"/>
      </children>
    </children>
    <children xsi:type="Element" name="category">
      <children xsi:type="Element" name="category">
        <children xsi:type="Element" name="domain">
          <children xsi:type="Text" name="thedomain" value="lesheme1"/>
        </children>
        <children xsi:type="Element" name="value">
          <children xsi:type="Text" name="thevalue" value="lelabel"/>
        </children>
      </children>
    </children>
    <children xsi:type="Element" name="docs">
      <children xsi:type="Text" name="thedocs" value=""/>
    </children>
    <children xsi:type="Element" name="ttl">
      <children xsi:type="Text" name="thettl" value=""/>
    </children>
    <children xsi:type="Element" name="rating">
      <children xsi:type="Text" name="therating" value=""/>
    </children>
  </Root>
  <Element name="category">
    <children xsi:type="Element" name="domain">
      <children xsi:type="Text" name="thedomain" value="lesheme2"/>
    </children>
    <children xsi:type="Element" name="value">
      <children xsi:type="Text" name="thevalue" value="lelabel"/>
    </children>
  </Element>
</xmi:XMI>
