<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="SVG">
    <eClassifiers xsi:type="ecore:EClass" name="LocatedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" ordered="false" unique="false" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="commentsBefore" unique="false" upperBound="-1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="commentsAfter" unique="false" upperBound="-1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Svg" eSuperTypes="/0/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="xmlns" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="standalone" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="test" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1" eType="/0/Element" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true" eSuperTypes="/0/LocatedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Group" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="translate_x" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="translate_y" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="components" ordered="false" lowerBound="1" upperBound="-1" eType="/0/Element" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Shape" eSuperTypes="/0/Element">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fill" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Rect" eSuperTypes="/0/Shape">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rx" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ry" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stroke" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stroke_width" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="opacity" ordered="false" unique="false" lowerBound="1" eType="/1/Double"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="/0/Shape">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="font_size" ordered="false" unique="false" lowerBound="1" eType="/1/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="font_family" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="contend" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Double"/>
  </ecore:EPackage>
</xmi:XMI>
